import offer1 from "./offer_1.jpg";
import offer2 from "./offer_2.jpg";
import offer3 from "./offer_3.jpg";
import offer4 from "./offer_4.jpg";
import offer5 from "./offer_5.jpg";
import offer6 from "./offer_6.jpg";
import offer7 from "./offer_7.jpg";
import offer8 from "./offer_8.jpg";
import offer9 from "./offer_9.jpg";
import offer10 from "./offer_10.jpg";

export const imageOffer1 = offer1;
export const imageOffer2 = offer2;
export const imageOffer3 = offer3;
export const imageOffer4 = offer4;
export const imageOffer5 = offer5;
export const imageOffer6 = offer6;
export const imageOffer7 = offer7;
export const imageOffer8 = offer8;
export const imageOffer9 = offer9;
export const imageOffer10 = offer10;
